[package]
name = "cli_app"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7.4"
arc_swap = "1.7.1"
clap = "4"
anyhow = "1"
config = "0.14"
dotenv = "0.15"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
